import type { Info, Settings } from "../api";

type Props = {
  info: Info | null;
  infoError: string | null;
  settings: Settings;
  onChange: (s: Settings) => void;
};

function Slider({
  label,
  value,
  min,
  max,
  step,
  hint,
  format,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  hint?: string;
  format?: (v: number) => string;
  onChange: (v: number) => void;
}) {
  return (
    <div>
      <div className="mb-1 flex items-baseline justify-between">
        <label className="text-sm font-medium text-ink-700">{label}</label>
        <span className="font-mono text-xs text-ink-500">
          {format ? format(value) : value}
        </span>
      </div>
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        className="w-full accent-accent"
      />
      {hint && <p className="mt-1 text-[11px] leading-snug text-ink-500">{hint}</p>}
    </div>
  );
}

export function Sidebar({ info, infoError, settings, onChange }: Props) {
  const set = (patch: Partial<Settings>) => onChange({ ...settings, ...patch });

  return (
    <aside className="flex h-full w-full flex-col gap-6 p-6">
      <div>
        <h1 className="text-base font-semibold text-ink-900">WoW RAG Pipeline</h1>
        <p className="mt-0.5 text-xs text-ink-500">
          Knowledge-grounded dialogue over Wizard of Wikipedia.
        </p>
        <div className="mt-3 flex flex-wrap gap-1.5">
          <span className="pill-accent">Ext 4 rewrite</span>
          <span className="pill-accent">Ext 3 cache</span>
          <span className="pill-accent">Stage 1 dense</span>
          <span className="pill-accent">Ext 1 props</span>
          <span className="pill-accent">Ext 2 rerank</span>
          <span className="pill-accent">Stage 2 GenKS</span>
          <span className="pill-accent">Stage 3 KEDiT</span>
          <span className="pill-accent">Stage 4 FLARE</span>
          <span className="pill-accent">Stage 5 Q²/BEGIN</span>
        </div>
      </div>

      <div>
        <p className="stage-h mb-2">Index</p>
        {infoError ? (
          <div className="card p-3 text-xs text-red-600">{infoError}</div>
        ) : info ? (
          <div className="grid grid-cols-2 gap-2">
            <div className="card p-3">
              <div className="text-[11px] text-ink-500">Parents</div>
              <div className="text-lg font-semibold text-ink-900">{info.parents}</div>
            </div>
            <div className="card p-3">
              <div className="text-[11px] text-ink-500">Propositions</div>
              <div className="text-lg font-semibold text-ink-900">{info.propositions}</div>
            </div>
          </div>
        ) : (
          <div className="card p-3 text-xs text-ink-500">Loading...</div>
        )}
      </div>

      <div className="space-y-5">
        <p className="stage-h">Settings</p>
        <Slider
          label="Dense pool size"
          hint="How many parents the dense retriever passes to the reranker."
          min={5}
          max={30}
          step={1}
          value={settings.dense_pool}
          onChange={(v) => set({ dense_pool: v })}
        />
        <Slider
          label="Props per query variant"
          min={5}
          max={50}
          step={5}
          value={settings.top_n_props}
          onChange={(v) => set({ top_n_props: v })}
        />
        <Slider
          label="Reranked top-K"
          hint="Final passages shown after reranking."
          min={1}
          max={10}
          step={1}
          value={settings.rerank_k}
          onChange={(v) => set({ rerank_k: v })}
        />
        <Slider
          label="Paraphrases"
          hint="Extra query variants generated by the rewriter."
          min={0}
          max={4}
          step={1}
          value={settings.n_paraphrases}
          onChange={(v) => set({ n_paraphrases: v })}
        />
        <Slider
          label="Answer temperature"
          min={0}
          max={1}
          step={0.05}
          value={settings.gen_temperature}
          format={(v) => v.toFixed(2)}
          onChange={(v) => set({ gen_temperature: v })}
        />
        <Slider
          label="Cache threshold τ"
          hint="Cosine similarity above which the dialogue cache skips dense+rerank+GenKS."
          min={0}
          max={1}
          step={0.05}
          value={settings.tau_cache}
          format={(v) => v.toFixed(2)}
          onChange={(v) => set({ tau_cache: v })}
        />
      </div>

      <div className="mt-auto pt-4 text-[11px] text-ink-400">
        Press <span className="kbd">⌘</span> + <span className="kbd">Enter</span> to run.
      </div>
    </aside>
  );
}
